DRIVER_CLASS=com.mysql.cj.jdbc.Driver
DB_USER=root
DB_CONNECTION_URL=jdbc:mysql://119.56.188.47:3306/mydb?characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
DB_PWD=kwom@9604844

